### ISSUE TITLE
ROS1 Services

### ISSUE THREAD

**Issue by PBerry-BDL** [lambdaprime/jros1client#1]
Hi, I may be missing something, but I can't see how to manage services in the ROS 1 client.  I see there's a repo for ROS 2 services, is it unsupported in ROS 1?

I see that MasterApiClientImpl has a method lookupService, are services handled the same way as topics? Could I get an example please?

**Comment by lambdaprime** [comment]
Hi @PBerry-BDL 
Thank you for the message.

You are right currently services are supported only in ROS2.

I will check how long it may take to implement them for ROS1 and will update you sometime next week.

Regards,

**Comment by lambdaprime** [comment]
Hi @PBerry-BDL 

I am planning to implement client to ROS1 services. I expect it be ready end of month.
This client will allow to send requests to ROS1 services but it will not support creating the actual ROS1 services which execute those requests.
Please let me know if it covers your use case.
Regards,

**Comment by PBerry-BDL** [comment]
@lambdaprime yes that's fine, this will be perfect thanks.

I'd like to contribute to this project, are there any dev-docs?

**Comment by lambdaprime** [comment]
Hi @PBerry-BDL 

Thank you, please see [Contributing to the JROS projects](http://portal2.atwebpages.com/jrosclient/contributing.html)

Regards,

**Comment by lambdaprime** [comment]
Hi @PBerry-BDL 

It is ready, you can find it here [jros1services](https://github.com/pinorobotics/jros1services)
